# sudo docker-compose up -d
# sudo docker attach cerberusdet_cerber_1
version: "3"

services:
  cerber:
    shm_size: 100G
    build: .
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
